---
- name: Install gpg package
  ansible.builtin.package:
    name: gpg
    state: present
    update_cache: true

- name: Add pwch group
  ansible.builtin.group:
    name: pwch
    state: present

- name: Add pwch user
  ansible.builtin.user:
    name: pwch
    groups:
      - pwch
    shell: /sbin/nologin
    create_home: false
    system: true
    state: present

- name: Create config directory
  ansible.builtin.file:
    path: /etc/pwch
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy config file to host
  ansible.builtin.template:
    src: config.yml.j2
    dest: /etc/pwch/config.yml
    owner: pwch
    group: pwch
    mode: 0640
  notify: Restart pwch

- name: Create assets directory
  ansible.builtin.file:
    path: /usr/local/src/pwch
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy assets to host
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /usr/local/src/pwch/{{ item }}
    owner: root
    group: root
    mode: 0644
  loop:
    - changePassword.html
    - error.html
    - submitEmail.html
    - success.html

- name: Download pwch checksum file and signature
  ansible.builtin.get_url:
    url: |
      {{ pwch_base_url }}/{{ pwch_version }}/pwch_{{ pwch_arch }}.{{ item }}
    dest: .
    force: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0644
  loop:
    - sha256
    - sha256.asc

- name: Copy public key to host
  ansible.builtin.copy:
    src: public.asc
    dest: public.asc
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0640

- name: Import public key
  ansible.builtin.command: gpg --import public.asc
  changed_when: false

- name: Verify checksum file
  ansible.builtin.command: |
    gpg --verify pwch_{{ pwch_arch }}.sha256.asc pwch_{{ pwch_arch }}.sha256
  register: verify
  changed_when: false
  failed_when: verify.rc != 0

- name: Read checksum file
  ansible.builtin.slurp:
    src: pwch_{{ pwch_arch }}.sha256
  register: checksums

- name: Extract hashes
  ansible.builtin.set_fact:
    pwch_checksums: |
      {{ checksums['content'] | b64decode | regex_findall('[0-9a-f]{64}') }}

- name: Download pwch binary from github
  ansible.builtin.get_url:
    url: "{{ pwch_base_url }}/{{ pwch_version }}/pwch_{{ pwch_arch }}"
    dest: /usr/local/bin/pwch
    owner: root
    group: root
    mode: 0755
    checksum: sha256:{{ pwch_checksums[0] }}
  notify: Restart pwch

- name: Download doveadm_wrapper binary from github
  ansible.builtin.get_url:
    url: |
      {{ pwch_base_url }}/{{ pwch_version }}/doveadm_wrapper_{{ pwch_arch }}
    dest: /usr/local/bin/doveadm_wrapper
    owner: root
    group: pwch
    mode: 04750
    checksum: sha256:{{ pwch_checksums[1] }}

- name: Copy unit file to host
  ansible.builtin.copy:
    src: pwch.service
    dest: /etc/systemd/system/pwch.service
    owner: root
    group: root
    mode: 0644
  notify: Reload systemd

- name: Copy apparmor profile to host
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: /etc/apparmor.d/usr.local.bin.{{ item.dest }}
    owner: root
    group: root
    mode: 0644
  register: apparmor_policy
  when: pwch_apparmor_enabled
  loop:
    - {src: apparmor_profile_pwch, dest: pwch}
    - {src: apparmor_profile_doveadm_wrapper, dest: doveadm_wrapper}

- name: Reload apparmor policies  # noqa no-handler
  ansible.builtin.command: >
    apparmor_parser -r /etc/apparmor.d/usr.local.bin.pwch
    /etc/apparmor.d/usr.local.bin.doveadm_wrapper
  when: apparmor_policy.changed

- name: Enable and start service
  ansible.builtin.systemd:
    name: pwch
    enabled: true
    state: started
    daemon_reload: true
